backend:
  name: git-gateway
  branch: principal

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "events"
    label: "Événements"
    file: "events.json"
    format: "json"
    fields:
      - { label: "Événements", name: "events", widget: "list", fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "string" }
          - { label: "Lieu", name: "location", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
        }
